### ISSUE TITLE
README needs formatting

### ISSUE THREAD

**Issue by daneah** [crawsome/PyMusicGen#1]
Hello! I'm always really interested in toying with music and sound with Python so I'm excited about your project!

I noticed that the README reads as essentially plain text at the moment; I'd be happy to markdown-ify it in a pull request if you're interested! If you want to open any known issues I'd be happy to contribute there as well.

**Comment by crawsome** [comment]
Hey Dan thank you so much for the advice.  I just started using GitHub and
I didn't know that Markdown was the default I'll be glad to change it
myself. Please expect to see changes soon thank you!!

**Comment by daneah** [comment]
Excellent! Feel free to reach out if you'd like any contributions :smile:

**Comment by crawsome** [comment]
The document is now marked-down. There's a couple formatting errors, I'll smooth them out tomorrow most likely. 

Thanks for your support.
