### ISSUE TITLE
Cleaning up code style

### ISSUE THREAD

**Issue by jlaurelli** [crawsome/PyMusicGen#2]
Hey Colin,

I'm James. We met at CPOSC yesterday. I said I'd take a gander over your code through the eyes of someone that has written Python professionally.

I haven't had much time yet to go into the nitty-gritty of it (though I can do that, too, if you'd like), but from skimming over it I think it may be worth your while to practice writing in the most common idiomatic Python style, that being in [PEP 8](https://www.python.org/dev/peps/pep-0008/).

A lot of dev shops that write Python in larger applications tend to use that guide as a foundation and then tweak it as needed. A common example is to generally try to keep lines under 80 characters, but it is OK if a line reads better that goes over this limitation. Exactly which guidelines you prefer to follow or not is entirely up to you.

It may seem a bit pedantic, but you will likely see A LOT of Python written like this.

There are also a few other high-level concepts you can implement that may save you some hair in the future (unit testing and in-code documentation, as examples), but honestly, the fact that you have something on GitHub that isn't on fire is a pretty good start as it is.

**Comment by crawsome** [comment]
Hi James! Great to hear from you. Thank you for your kind and constructive words.

I will start work into making it adhere to PEP-8 standards.

Have a great holiday. 

CB

**Comment by crawsome** [comment]
Since then, I have optimized it a lot and boiled it down to the important parts. I will be retiring this soon and looking into a true MIDI implementation soon. 

I will close it for now, as it now adheres to PEP 8. 

Thanks for all your help.
